#!/bin/bash

VERCEL_ORG_ID=
VERCEL_PROJECT_ID=
# VERCEL_TOKEN="...set in release..."

npm install --global vercel@latest
vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
vercel build --token=${VERCEL_TOKEN}
vercel deploy --prebuilt --token=${VERCEL_TOKEN}
