version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend
    ports:
      - "9293:9293"
    environment:
      - GROMIT_BACKEND_URL=http://backend:3000
      - OPENAI_KEY=your_openai_api_key

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379"
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:
  redis_data:
